# Storage network - DHCP, but lower routing preference
# enp1s0
#   sudo curl https://gitlab.com/cssl/NetChris/public/linux/raw/master/etc/netplan/20-enp1s0-storage.yaml -o /etc/netplan/20-enp1s0-storage.yaml
#   sudo netplan generate
#   sudo netplan try
# If the countdown timer continues, you know you have it right ...
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: yes
      dhcp4-overrides:
        route-metric: 200
